[target.x86_64-pc-windows-gnullvm]
linker = ".toolchains/llvm-mingw-20260505-ucrt-x86_64/bin/x86_64-w64-mingw32-clang.exe"
ar = ".toolchains/llvm-mingw-20260505-ucrt-x86_64/bin/llvm-ar.exe"
rustflags = [
    "-Clink-arg=--sysroot=.toolchains/llvm-mingw-20260505-ucrt-x86_64/x86_64-w64-mingw32",
    "-Clink-arg=.toolchains/llvm-mingw-20260505-ucrt-x86_64/x86_64-w64-mingw32/lib/libmingw32.a",
    "-Clink-arg=.toolchains/llvm-mingw-20260505-ucrt-x86_64/x86_64-w64-mingw32/lib/libmingwex.a",
    "-Clink-arg=-Wl,--allow-multiple-definition",
]

[target.x86_64-pc-windows-gnullvm.env]
PKG_CONFIG = "C:\\msys64\\mingw64\\bin\\pkg-config.exe"
PKG_CONFIG_PATH = "C:\\msys64\\mingw64\\lib\\pkgconfig"
PKG_CONFIG_ALLOW_SYSTEM_LIBS = "1"
PKG_CONFIG_ALLOW_SYSTEM_CFLAGS = "1"
LIBCLANG_PATH = "C:\\msys64\\mingw64\\bin"